# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79485ac66448c16855506d76b3948dca3e530e1b10310d9990297697c7373e871c35cc8744e21537a513ad2093070ec4fbee4c24ef8f6b50e99fb0ca5099399d

test:
  secret_key_base: 46b675cb84491026b61327b9cde35cd12d9ba97ad67c1682ee07b0a0a09463c504f0e3ec4f0511efd41475156d85aa707635145b0a43ebf4aed35908378df041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
